### ISSUE TITLE
Components not working in 7.93

### ISSUE THREAD

**Issue by TheWolfinator** [Pinegrow/PinegrowReleases#1]
create a new project using pinegrow 7.93
from the templates choose bootstrap 5
click on the + icon and navigate to the components tab
error message is displayed

components is working in 7.92

**Comment by matjaztrontelj** [comment]
@TheWolfinator thanks for reporting this. It is fixed, just restart Pinegrow.
Will close issues here because we want to keep all bug reports in the same place on our forum.
